"""HyperForecaster: Hypernetwork for adaptive time-series forecasting.

Key idea:
  Standard neural networks use the same shared weights for every input sample.
  HyperForecaster instead generates *sample-specific* target network weights
  conditioned on the input — allowing the model to adapt its computation per sample:

      Context encoder:  x  →  z            (B*C, d_ctx) shared MLP
      HyperNet:         z  →  θ(z)          (B*C, n_target_params) linear map
      Target network:   x  → ŷ  using θ(z)  (2-layer MLP with per-sample weights)

  The target network is a simple two-layer MLP with GELU activation; its weights and
  biases are generated by the hyper-network for every (batch element × variate) pair.

  Concretely, for sample b:
      W1(b), b1(b) = split(θ(z_b))             # first-layer weight + bias
      W2(b), b2(b) = split(θ(z_b))             # second-layer weight + bias
      h(b) = GELU( x_b W1(b) + b1(b) )        # target forward pass
      ŷ(b) = h(b) W2(b) + b2(b)

  The einsum formulation makes this differentiable; gradients flow through both the
  context encoder and the hyper-network.

Architecture comparison:
  DLinear/NLinear: shared fixed linear weights for all samples.
  MoEForecaster:   shared expert weights, per-sample routing.
  HyperForecaster: fully per-sample weights generated from context — no weight sharing
                   in the target network at all.

Args:
    seq_len:    lookback T.
    pred_len:   forecast horizon.
    enc_in:     number of variates.
    d_ctx:      context encoding dimension.
    hidden:     hidden size of target network.
    d_ctx_hidden: hidden size of context encoder.
    dropout:    dropout in context encoder.
    revin:      use RevIN normalisation.
"""
from __future__ import annotations

import torch
import torch.nn as nn
import torch.nn.functional as F


# ──────────────────────────────────────────────────────────────────────────────
# RevIN
# ──────────────────────────────────────────────────────────────────────────────


class _RevIN(nn.Module):
    def __init__(self, num_features: int, eps: float = 1e-5):
        super().__init__()
        self.eps = eps
        self.affine_weight = nn.Parameter(torch.ones(num_features))
        self.affine_bias = nn.Parameter(torch.zeros(num_features))

    def forward(self, x: torch.Tensor, mode: str) -> torch.Tensor:
        if mode == "norm":
            self._mean = x.mean(1, keepdim=True)
            self._std = x.std(1, keepdim=True).clamp(self.eps)
            x = (x - self._mean) / self._std
            return x * self.affine_weight + self.affine_bias
        else:
            x = (x - self.affine_bias) / (self.affine_weight + self.eps)
            return x * self._std + self._mean


# ──────────────────────────────────────────────────────────────────────────────
# HyperForecaster
# ──────────────────────────────────────────────────────────────────────────────


class HyperForecaster(nn.Module):
    """Hypernetwork-based adaptive forecaster (channel-independent)."""

    def __init__(
        self,
        seq_len: int,
        pred_len: int,
        enc_in: int,
        d_ctx: int = 64,
        hidden: int = 32,
        d_ctx_hidden: int = 128,
        dropout: float = 0.1,
        revin: bool = True,
    ):
        super().__init__()
        self.seq_len = seq_len
        self.pred_len = pred_len
        self.enc_in = enc_in
        self.hidden = hidden
        self._revin_flag = revin

        if revin:
            self.revin_layer = _RevIN(enc_in)

        # Context encoder: maps (B*C, T) → (B*C, d_ctx)
        self.ctx_encoder = nn.Sequential(
            nn.Linear(seq_len, d_ctx_hidden),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(d_ctx_hidden, d_ctx),
        )

        # Compute target-network parameter counts
        # Layer 1: (seq_len → hidden)  → W1: seq_len*hidden, b1: hidden
        # Layer 2: (hidden → pred_len) → W2: hidden*pred_len, b2: pred_len
        w1 = seq_len * hidden
        w2 = hidden * pred_len
        n_params = w1 + hidden + w2 + pred_len

        # HyperNet: (d_ctx → n_params) linear
        self.hyper_net = nn.Linear(d_ctx, n_params)

        # Store split indices
        self._w1 = w1
        self._w2 = w2
        self._b1 = hidden
        self._b2 = pred_len
        self._n_params = n_params

        # Small gain for init: keep generated weights O(1/sqrt(fan_in))
        nn.init.normal_(self.hyper_net.weight, std=0.01)
        nn.init.zeros_(self.hyper_net.bias)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Args:
            x: (B, T, C)
        Returns:
            (B, pred_len, C)
        """
        B, T, C = x.shape

        if self._revin_flag:
            x = self.revin_layer(x, "norm")

        x_ci = x.transpose(1, 2).reshape(B * C, T)              # (BC, T)

        # ── Generate target weights ───────────────────────────────────────────
        ctx = self.ctx_encoder(x_ci)                             # (BC, d_ctx)
        params = self.hyper_net(ctx)                             # (BC, n_params)

        # Split and reshape parameter vector
        i = 0
        W1 = params[:, i : i + self._w1].reshape(
            B * C, T, self.hidden
        )                                                        # (BC, T, hidden)
        i += self._w1
        b1 = params[:, i : i + self._b1]                        # (BC, hidden)
        i += self._b1
        W2 = params[:, i : i + self._w2].reshape(
            B * C, self.hidden, self.pred_len
        )                                                        # (BC, hidden, pred_len)
        i += self._w2
        b2 = params[:, i : i + self._b2]                        # (BC, pred_len)

        # ── Target network forward pass (per-sample weights) ──────────────────
        h = torch.einsum("bi, bij -> bj", x_ci, W1) + b1        # (BC, hidden)
        h = F.gelu(h)
        out = torch.einsum("bi, bij -> bj", h, W2) + b2         # (BC, pred_len)

        out = out.reshape(B, C, self.pred_len).transpose(1, 2)  # (B, pred_len, C)

        if self._revin_flag:
            out = self.revin_layer(out, "denorm")
        return out
